// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProyectoFinalPOO2;

#nullable disable

namespace ProyectoFinalPOO2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinalPOO2.Entities.Jefe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Departamento")
                        .HasColumnType("text");

                    b.Property<string>("NombreJefe")
                        .HasColumnType("text");

                    b.Property<int>("Sueldo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Jefes");
                });

            modelBuilder.Entity("ProyectoFinalPOO2.Entities.LoginEncargado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContraseñaEnc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorreoEnc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoginEncargados");
                });

            modelBuilder.Entity("ProyectoFinalPOO2.Entities.RegEmpleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Curp")
                        .HasColumnType("text");

                    b.Property<string>("Departamento")
                        .HasColumnType("text");

                    b.Property<string>("Domicilio")
                        .HasColumnType("text");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaNac")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Jefe")
                        .HasColumnType("text");

                    b.Property<Guid?>("JefeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("text");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("text");

                    b.Property<string>("Rfc")
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JefeId");

                    b.ToTable("RegEmpleados");
                });

            modelBuilder.Entity("ProyectoFinalPOO2.Entities.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("ProyectoFinalPOO2.Entities.RegEmpleado", b =>
                {
                    b.HasOne("ProyectoFinalPOO2.Entities.Jefe", "Jefe1")
                        .WithMany("Jefes")
                        .HasForeignKey("JefeId");

                    b.Navigation("Jefe1");
                });

            modelBuilder.Entity("ProyectoFinalPOO2.Entities.Jefe", b =>
                {
                    b.Navigation("Jefes");
                });
#pragma warning restore 612, 618
        }
    }
}
